// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjYGvOm5vxCCvkko5elBXhs50JKlvrBD4',
    appId: '1:879613419364:web:af560f2ede11c1cfc76471',
    messagingSenderId: '879613419364',
    projectId: 'barcanews-62f4d',
    authDomain: 'barcanews-62f4d.firebaseapp.com',
    storageBucket: 'barcanews-62f4d.firebasestorage.app',
    measurementId: 'G-GC3WFGFGH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoF30KP6c6_CvvyKQ3t6JMa_TTjSbgfDs',
    appId: '1:879613419364:android:1c057e7de5e1300cc76471',
    messagingSenderId: '879613419364',
    projectId: 'barcanews-62f4d',
    storageBucket: 'barcanews-62f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xwLBl1bFd6aBbHUZklwoqVJbgKa6adE',
    appId: '1:879613419364:ios:e0e6ca62f07488ebc76471',
    messagingSenderId: '879613419364',
    projectId: 'barcanews-62f4d',
    storageBucket: 'barcanews-62f4d.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xwLBl1bFd6aBbHUZklwoqVJbgKa6adE',
    appId: '1:879613419364:ios:e0e6ca62f07488ebc76471',
    messagingSenderId: '879613419364',
    projectId: 'barcanews-62f4d',
    storageBucket: 'barcanews-62f4d.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjYGvOm5vxCCvkko5elBXhs50JKlvrBD4',
    appId: '1:879613419364:web:97ef9f39ed21495fc76471',
    messagingSenderId: '879613419364',
    projectId: 'barcanews-62f4d',
    authDomain: 'barcanews-62f4d.firebaseapp.com',
    storageBucket: 'barcanews-62f4d.firebasestorage.app',
    measurementId: 'G-2X961NSY4M',
  );
}
